from tkinter import *
root = Tk( )
root.geometry("3x4")
root.title('calculator')
root.configure(bg="red")
fnum=Label(root,text="First Number",fg="aqua",bg="yellow",bd="2",font=("Arial",8,"italic"))
txtname=Entry(root,bd="3px",bg="purple",fg='white',width="30")
snum=Label(root,text="Second Number",fg="aqua",bg="yellow",bd="2",font=("Arial",8,"italic"))
txtnum=Entry(root,bd="3px",bg="magenta",fg='white',width="30")
res=Label(root,text="Result",fg="aqua",bg="yellow",bd="2",font=("Arial",8,"italic"))
txtres=Entry(root,bd="3px",bg="black",fg='white',width="30")
btnadd=Button(root,text="Add")
btnsub=Button(root,text="Sub")
btnmult=Button(root,text="mult")
btndiv=Button(root,text="Div")
btnreset=Button(root,text="Reset")
btnexit=Button(root,text="Exit")
fnum.grid(row="0",column="0")
txtname.grid(row="0",column="1")
snum.grid(row="1",column="0")
txtnum.grid(row="1",column="1")
res.grid(row="2",column="0")
txtres.grid(row="2",column="1")
btnadd.grid(row="3",column="0")
btnsub.grid(row="3",column="1")
btnmult.grid(row="4",column="0")
btndiv.grid(row="4",column="1")
btnreset.grid(row="5",column="0")
btnexit.grid(row="5",column="1")
root.mainloop()