from tkinter import *
root=Tk( )
root.geometry("3x4")
root.title("Window")
lblname=Label(root,text="Enter Your Name",fg="aqua",bg="yellow",bd="2")
txtname=Entry(root,bd='3')
lblemail=Label(root,text="Email Id",fg="aqua",bg="yellow",bd="2")
txtemail=Entry(root,bd='3')
lblmobile=Label(root,text="Enter Mobile Number",fg="aqua",bg="yellow",bd="2")
txtmobile=Entry(root,bd='3')
btnclick=Button(root,text="Click")
#lblname.pack(side=BOTTOM)
#txtname.pack( )
#btnclick.pack( )
lblname.grid(row="0",column="0",pady="5")
txtname.grid(row="0",column="1",pady="5")
lblemail.grid(row="1",column="0",pady="5")
txtemail.grid(row="1",column="1",pady="5")
lblmobile.grid(row="2",column="0",pady="5")
txtmobile.grid(row="2",column="1",pady="5")
btnclick.grid(row="3",column="0")
root.mainloop( )