p=input("Enter Product name: ")
q=int(input("Enter product quantity: "))
r=int(input("Enter product price: "))
t=q*r
print("***********BILL***********")
#print("\n")
print("product\t Quantity\t Price")
print(p,"\t",q,"\t",r)
#print("\n")
print("*********************************")
#print("\n")
print("Total Amount To be paid:",t)
#print("\n")
print("************_____***********")