n=input("Enter employee's name :")
p=input("Enter post :")
s=int(input("Enter Salary :"))
h=int(s*10/100)
t=h
#t=int(s*10/100)
ts=(s+h+t)
print("\n")
print("Name of employee :",n)
print("post :",p)
print('Basic salary :',s)
print('HRA :',h)
print("TA :",t)
print("Total Salary :",ts)
print("**********----------**********")