s='I AM LEARNING PYTHON'
'''print(s.lower())
#print(s.upper())
print(s.title())
#print(s.casefold())
print(s.capitalize())
#print(s.center())
print(s.count('N'))
#print(s.find('M'))
#print(s.encode())
#print(s.expandtabs())
print(s.isupper())
print(s.swapcase())
print(s.zfill(len(s)+2))
print(s.replace('A','a'))'
print(s.split(' ',1))
print(s.split(' ',2))
print(s.split(' ',3))
print(s.split(' ',4))
#print(s.split(' ',5))
#print(s.split(' ',6))
print(s.count(''))'''
s1=s.split()
s2=' '.join(s1)
print(s1)
print(s2)